name: Run Audit

on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Run NPM Audit
        working-directory: "./TP3/with SQL/srv"
        run: npm audit